config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  resources :articles
  get 'react_examples/component', to: 'react_examples#component', as: :component
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :published_at)
    end
end

app/controllers/react_examples_controller.rb
class ReactExamplesController < ApplicationController
  def component
    @name = 'test'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<div class="mdl-color-text--primary-contrast mdl-card__supporting-text comments">
  <form>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <textarea rows=1 class="mdl-textfield__input" id="comment"></textarea>
      <label for="comment" class="mdl-textfield__label">Join the discussion</label>
    </div>
    <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
      <i class="material-icons" role="presentation">check</i><span class="visuallyhidden">add comment</span>
    </button>
  </form>
  <div class="comment mdl-color-text--grey-700">
    <header class="comment__header">
      <img src="images/co1.jpg" class="comment__avatar">
      <div class="comment__author">
        <strong>James Splayd</strong>
        <span>2 days ago</span>
      </div>
    </header>
    <div class="comment__text">
      In in culpa nulla elit esse. Ex cillum enim aliquip sit sit ullamco ex eiusmod fugiat. Cupidatat ad minim
      officia mollit laborum magna dolor tempor cupidatat mollit. Est velit sit ad aliqua ullamco laborum
      excepteur dolore proident incididunt in labore elit.
    </div>
    <nav class="comment__actions">
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
        <i class="material-icons" role="presentation">thumb_up</i><span class="visuallyhidden">like comment</span>
      </button>
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
        <i class="material-icons" role="presentation">thumb_down</i><span class="visuallyhidden">dislike comment</span>
      </button>
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
        <i class="material-icons" role="presentation">share</i><span class="visuallyhidden">share comment</span>
      </button>
    </nav>
    <div class="comment__answers">
      <div class="comment">
        <header class="comment__header">
          <img src="images/co2.jpg" class="comment__avatar">
          <div class="comment__author">
            <strong>John Dufry</strong>
            <span>2 days ago</span>
          </div>
        </header>
        <div class="comment__text">
          Yep, agree!
        </div>
        <nav class="comment__actions">
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
            <i class="material-icons" role="presentation">thumb_up</i><span class="visuallyhidden">like comment</span>
          </button>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
            <i class="material-icons" role="presentation">thumb_down</i><span class="visuallyhidden">dislike comment</span>
          </button>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
            <i class="material-icons" role="presentation">share</i><span class="visuallyhidden">share comment</span>
          </button>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/articles/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer--left-section">
    <button class="mdl-mini-footer--social-btn social-btn social-btn__twitter">
      <span class="visuallyhidden">Twitter</span>
    </button>
    <button class="mdl-mini-footer--social-btn social-btn social-btn__blogger">
      <span class="visuallyhidden">Facebook</span>
    </button>
    <button class="mdl-mini-footer--social-btn social-btn social-btn__gplus">
      <span class="visuallyhidden">Google Plus</span>
    </button>
  </div>
  <div class="mdl-mini-footer--right-section">
    <button class="mdl-mini-footer--social-btn social-btn__share">
      <i class="material-icons" role="presentation">share</i>
      <span class="visuallyhidden">share</span>
    </button>
  </div>
</footer>

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_nav.html.erb
<nav class="demo-nav mdl-color-text--grey-50 mdl-cell mdl-cell--12-col">
  <a href="index.html" class="demo-nav__button">
    <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white mdl-color-text--grey-900" role="presentation">
      <i class="material-icons">arrow_back</i>
    </button>
    Newer
  </a>
  <div class="section-spacer"></div>
  <a href="index.html" class="demo-nav__button">
    Older
    <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white mdl-color-text--grey-900" role="presentation">
      <i class="material-icons">arrow_forward</i>
    </button>
  </a>
</nav>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= react_component 'ArticlesPage', { foo: 'bar' } %>

hey

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="demo-blog demo-blog--blogpost mdl-layout mdl-js-layout has-drawer is-upgraded">
  <main class="mdl-layout__content">
    <div class="demo-back">
      <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" href="index.html" title="go back" role="button">
        <i class="material-icons" role="presentation">arrow_back</i>
      </a>
    </div>
    <div class="demo-blog__posts mdl-grid">
      <div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col">
        <div class="mdl-card__media mdl-color-text--grey-50">
          <h3><%= @article.title %></h3>
        </div>
        <div class="mdl-color-text--grey-700 mdl-card__supporting-text meta">
          <div class="minilogo"></div>
          <div>
            <strong>The Newist</strong>
            <span>2 days ago</span>
          </div>
          <div class="section-spacer"></div>
          <div class="meta__favorites">
            425 <i class="material-icons" role="presentation">favorite</i>
            <span class="visuallyhidden">favorites</span>
          </div>
          <div>
            <i class="material-icons" role="presentation">bookmark</i>
            <span class="visuallyhidden">bookmark</span>
          </div>
          <div>
            <i class="material-icons" role="presentation">share</i>
            <span class="visuallyhidden">share</span>
          </div>
        </div>
        <div class="mdl-color-text--grey-700 mdl-card__supporting-text">
          <%= @article.content.html_safe %>
        </div>
        <%= render 'comments' %>
      </div>

      <%= render 'nav' %>
    </div>
    <%= render 'footer' %>
  </main>
  <div class="mdl-layout__obfuscator"></div>
</div>

app/views/layouts/_react_hot_assets.html.erb
<% if Rails.env.development? %>
  <script src='http://localhost:8080/assets/react_bundle.js'></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lukatonia</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <title>Material Design Lite</title>

  <!-- Add to homescreen for Chrome on Android -->
  <meta name="mobile-web-app-capable" content="yes">

  <!-- Add to homescreen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Material Design Lite">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/react_hot_assets' %>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">


  <main class="">
    <%= react_component 'App', {} %>
  </main>
</div>
<script src="https://code.getmdl.io/1.1.3/material.min.js"></script>

</body>
</html>

app/views/react_examples/component.html.erb
<%= react_component('HelloWorld', { name: @name }, { server_side: true }) %>